//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuctionsPortal.Service.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public Item()
        {
            this.Bidding = new HashSet<Bidding>();
            this.ItemImage = new HashSet<ItemImage>();
        }
    
        public int ItemId { get; set; }
        public string Name { get; set; }
        public int CategoryId { get; set; }
        public int AdvetiserId { get; set; }
        public string Description { get; set; }
        public int StartingCall { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime CloseDate { get; set; }
    
        public virtual Advetiser Advetiser { get; set; }
        public virtual ICollection<Bidding> Bidding { get; set; }
        public virtual Category Category { get; set; }
        public virtual ICollection<ItemImage> ItemImage { get; set; }
    }
}
