//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuctionsPortal.Service.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemImage
    {
        public int ImageId { get; set; }
        public int ItemId { get; set; }
        public byte[] Image { get; set; }
    
        public virtual Item Item { get; set; }
    }
}
