//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuctionsPortal.Service.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public Users()
        {
            this.Bidding = new HashSet<Bidding>();
        }
    
        public int UserId { get; set; }
        public string Name { get; set; }
        public byte[] Password { get; set; }
        public string UserName { get; set; }
        public string PhoneNumber { get; set; }
        public string EMail { get; set; }
    
        public virtual ICollection<Bidding> Bidding { get; set; }
    }
}
